<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace AntibodiesOnline\FedEx\Model;

class AvailabilityV1SpecialserviceoptionsPostResponse200OutputServiceOptionsListItemSignatureOptionsListItem extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * Display Text.
     *
     * @var string
     */
    protected $displayText;
    /**
     * Unique code.
     *
     * @var string
     */
    protected $code;

    /**
     * Display Text.
     */
    public function getDisplayText(): string
    {
        return $this->displayText;
    }

    /**
     * Display Text.
     */
    public function setDisplayText(string $displayText): self
    {
        $this->initialized['displayText'] = true;
        $this->displayText = $displayText;

        return $this;
    }

    /**
     * Unique code.
     */
    public function getCode(): string
    {
        return $this->code;
    }

    /**
     * Unique code.
     */
    public function setCode(string $code): self
    {
        $this->initialized['code'] = true;
        $this->code = $code;

        return $this;
    }
}
