<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace AntibodiesOnline\FedEx\Model;

class AvailabilityV1TransittimesPostResponse200OutputtransitTimesItem extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * Specifies the details regarding transit times.
     *
     * @var list<AvailabilityV1TransittimesPostResponse200OutputtransitTimesItemTransitTimeDetailsItem>
     */
    protected $transitTimeDetails;

    /**
     * Specifies the details regarding transit times.
     *
     * @return list<AvailabilityV1TransittimesPostResponse200OutputtransitTimesItemTransitTimeDetailsItem>
     */
    public function getTransitTimeDetails(): array
    {
        return $this->transitTimeDetails;
    }

    /**
     * Specifies the details regarding transit times.
     *
     * @param list<AvailabilityV1TransittimesPostResponse200OutputtransitTimesItemTransitTimeDetailsItem> $transitTimeDetails
     */
    public function setTransitTimeDetails(array $transitTimeDetails): self
    {
        $this->initialized['transitTimeDetails'] = true;
        $this->transitTimeDetails = $transitTimeDetails;

        return $this;
    }
}
