<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace AntibodiesOnline\FedEx\Model;

class AvailabilityV1PackageandserviceoptionsPostResponse200OutputPackageOptionsItemPackageType extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * Display Text.
     */
    protected $displayText;
    /**
     * Unique Key.
     */
    protected $key;

    /**
     * Display Text.
     */
    public function getDisplayText()
    {
        return $this->displayText;
    }

    /**
     * Display Text.
     */
    public function setDisplayText($displayText): self
    {
        $this->initialized['displayText'] = true;
        $this->displayText = $displayText;

        return $this;
    }

    /**
     * Unique Key.
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * Unique Key.
     */
    public function setKey($key): self
    {
        $this->initialized['key'] = true;
        $this->key = $key;

        return $this;
    }
}
