<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace AntibodiesOnline\FedEx\Model;

class AvailabilityV1TransittimesPostResponse200OutputtransitTimesItemTransitTimeDetailsItemCommitDateDetail extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * This is a day of week in a shorter day format<br>Example: MON, TUE.
     *
     * @var string
     */
    protected $dayOfWeek;
    /**
     * This is time in a day. <br> Format: [HH:MM:SS]<br>example: 09:30:00.
     *
     * @var string
     */
    protected $time;
    /**
     * This is the day in format [MM-DD-YYYY]<br>example: Apr-13-2021.
     *
     * @var string
     */
    protected $day;

    /**
     * This is a day of week in a shorter day format<br>Example: MON, TUE.
     */
    public function getDayOfWeek(): string
    {
        return $this->dayOfWeek;
    }

    /**
     * This is a day of week in a shorter day format<br>Example: MON, TUE.
     */
    public function setDayOfWeek(string $dayOfWeek): self
    {
        $this->initialized['dayOfWeek'] = true;
        $this->dayOfWeek = $dayOfWeek;

        return $this;
    }

    /**
     * This is time in a day. <br> Format: [HH:MM:SS]<br>example: 09:30:00.
     */
    public function getTime(): string
    {
        return $this->time;
    }

    /**
     * This is time in a day. <br> Format: [HH:MM:SS]<br>example: 09:30:00.
     */
    public function setTime(string $time): self
    {
        $this->initialized['time'] = true;
        $this->time = $time;

        return $this;
    }

    /**
     * This is the day in format [MM-DD-YYYY]<br>example: Apr-13-2021.
     */
    public function getDay(): string
    {
        return $this->day;
    }

    /**
     * This is the day in format [MM-DD-YYYY]<br>example: Apr-13-2021.
     */
    public function setDay(string $day): self
    {
        $this->initialized['day'] = true;
        $this->day = $day;

        return $this;
    }
}
