<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace AntibodiesOnline\FedEx\Model;

class DocumentsV1EtdsUploadPostResponse201 extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * This is the output received for a document upload request.
     *
     * @var DocumentsV1EtdsUploadPostResponse201Output
     */
    protected $output;
    /**
     * This element has a unique identifier added in your request, helps you match the request to the reply. <br> Example:XXXX_XXX123XXXXX.
     *
     * @var string
     */
    protected $customerTransactionId;

    /**
     * This is the output received for a document upload request.
     */
    public function getOutput(): DocumentsV1EtdsUploadPostResponse201Output
    {
        return $this->output;
    }

    /**
     * This is the output received for a document upload request.
     */
    public function setOutput(DocumentsV1EtdsUploadPostResponse201Output $output): self
    {
        $this->initialized['output'] = true;
        $this->output = $output;

        return $this;
    }

    /**
     * This element has a unique identifier added in your request, helps you match the request to the reply. <br> Example:XXXX_XXX123XXXXX.
     */
    public function getCustomerTransactionId(): string
    {
        return $this->customerTransactionId;
    }

    /**
     * This element has a unique identifier added in your request, helps you match the request to the reply. <br> Example:XXXX_XXX123XXXXX.
     */
    public function setCustomerTransactionId(string $customerTransactionId): self
    {
        $this->initialized['customerTransactionId'] = true;
        $this->customerTransactionId = $customerTransactionId;

        return $this;
    }
}
