<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace AntibodiesOnline\FedEx\Model;

class DocumentsV1LhsimagesUploadPostResponse201OutputMeta extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * Returns the path which is specified in the request. <br>Example: SIGNATURE.
     *
     * @var string
     */
    protected $imageType;
    /**
     * Returns the image index that is specified in the request.<br>            Example: IMAGE_1.
     *
     * @var string
     */
    protected $imageIndex;

    /**
     * Returns the path which is specified in the request. <br>Example: SIGNATURE.
     */
    public function getImageType(): string
    {
        return $this->imageType;
    }

    /**
     * Returns the path which is specified in the request. <br>Example: SIGNATURE.
     */
    public function setImageType(string $imageType): self
    {
        $this->initialized['imageType'] = true;
        $this->imageType = $imageType;

        return $this;
    }

    /**
     * Returns the image index that is specified in the request.<br>            Example: IMAGE_1.
     */
    public function getImageIndex(): string
    {
        return $this->imageIndex;
    }

    /**
     * Returns the image index that is specified in the request.<br>            Example: IMAGE_1.
     */
    public function setImageIndex(string $imageIndex): self
    {
        $this->initialized['imageIndex'] = true;
        $this->imageIndex = $imageIndex;

        return $this;
    }
}
