<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace AntibodiesOnline\FedEx\Model;

class GlobaltradeV1ShipmentsRegulatorydetailsRetrievePostResponse200OutputCountryDetailsshipmentDetailsregulatoryStatements extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * Object representing the information needed during the interaction with clients.
     *
     * @var GlobaltradeV1ShipmentsRegulatorydetailsRetrievePostResponse200OutputCountryDetailsshipmentDetailsregulatoryStatementsUserMessage
     */
    protected $userMessage;
    /**
     * This represents document support type.
     *
     * @var string
     */
    protected $supportType;
    /**
     * Specifies a requirement type.
     *
     * @var string
     */
    protected $allowability;
    /**
     * This represents file name.
     *
     * @var string
     */
    protected $fileName;
    /**
     * Represents agency url.
     *
     * @var string
     */
    protected $agencyUrl;
    /**
     * Represents document url.
     *
     * @var string
     */
    protected $documentUrl;
    /**
     * This specifies Regualatory document id.
     *
     * @var string
     */
    protected $id;
    /**
     * This specifies completion type.
     *
     * @var string
     */
    protected $completionType;
    /**
     * It Specifies agency name.
     *
     * @var string
     */
    protected $agencyName;
    /**
     * Specifies the localized attribute details.
     *
     * @var GlobaltradeV1ShipmentsRegulatorydetailsRetrievePostResponse200OutputCountryDetailsshipmentDetailsregulatoryStatementsLocalizedAttributes
     */
    protected $localizedAttributes;
    /**
     * Specifies the document identifier.
     *
     * @var list<string>
     */
    protected $documentIds;
    /**
     * This represents statement url.
     *
     * @var string
     */
    protected $statementUrl;

    /**
     * Object representing the information needed during the interaction with clients.
     */
    public function getUserMessage(): GlobaltradeV1ShipmentsRegulatorydetailsRetrievePostResponse200OutputCountryDetailsshipmentDetailsregulatoryStatementsUserMessage
    {
        return $this->userMessage;
    }

    /**
     * Object representing the information needed during the interaction with clients.
     */
    public function setUserMessage(GlobaltradeV1ShipmentsRegulatorydetailsRetrievePostResponse200OutputCountryDetailsshipmentDetailsregulatoryStatementsUserMessage $userMessage): self
    {
        $this->initialized['userMessage'] = true;
        $this->userMessage = $userMessage;

        return $this;
    }

    /**
     * This represents document support type.
     */
    public function getSupportType(): string
    {
        return $this->supportType;
    }

    /**
     * This represents document support type.
     */
    public function setSupportType(string $supportType): self
    {
        $this->initialized['supportType'] = true;
        $this->supportType = $supportType;

        return $this;
    }

    /**
     * Specifies a requirement type.
     */
    public function getAllowability(): string
    {
        return $this->allowability;
    }

    /**
     * Specifies a requirement type.
     */
    public function setAllowability(string $allowability): self
    {
        $this->initialized['allowability'] = true;
        $this->allowability = $allowability;

        return $this;
    }

    /**
     * This represents file name.
     */
    public function getFileName(): string
    {
        return $this->fileName;
    }

    /**
     * This represents file name.
     */
    public function setFileName(string $fileName): self
    {
        $this->initialized['fileName'] = true;
        $this->fileName = $fileName;

        return $this;
    }

    /**
     * Represents agency url.
     */
    public function getAgencyUrl(): string
    {
        return $this->agencyUrl;
    }

    /**
     * Represents agency url.
     */
    public function setAgencyUrl(string $agencyUrl): self
    {
        $this->initialized['agencyUrl'] = true;
        $this->agencyUrl = $agencyUrl;

        return $this;
    }

    /**
     * Represents document url.
     */
    public function getDocumentUrl(): string
    {
        return $this->documentUrl;
    }

    /**
     * Represents document url.
     */
    public function setDocumentUrl(string $documentUrl): self
    {
        $this->initialized['documentUrl'] = true;
        $this->documentUrl = $documentUrl;

        return $this;
    }

    /**
     * This specifies Regualatory document id.
     */
    public function getId(): string
    {
        return $this->id;
    }

    /**
     * This specifies Regualatory document id.
     */
    public function setId(string $id): self
    {
        $this->initialized['id'] = true;
        $this->id = $id;

        return $this;
    }

    /**
     * This specifies completion type.
     */
    public function getCompletionType(): string
    {
        return $this->completionType;
    }

    /**
     * This specifies completion type.
     */
    public function setCompletionType(string $completionType): self
    {
        $this->initialized['completionType'] = true;
        $this->completionType = $completionType;

        return $this;
    }

    /**
     * It Specifies agency name.
     */
    public function getAgencyName(): string
    {
        return $this->agencyName;
    }

    /**
     * It Specifies agency name.
     */
    public function setAgencyName(string $agencyName): self
    {
        $this->initialized['agencyName'] = true;
        $this->agencyName = $agencyName;

        return $this;
    }

    /**
     * Specifies the localized attribute details.
     */
    public function getLocalizedAttributes(): GlobaltradeV1ShipmentsRegulatorydetailsRetrievePostResponse200OutputCountryDetailsshipmentDetailsregulatoryStatementsLocalizedAttributes
    {
        return $this->localizedAttributes;
    }

    /**
     * Specifies the localized attribute details.
     */
    public function setLocalizedAttributes(GlobaltradeV1ShipmentsRegulatorydetailsRetrievePostResponse200OutputCountryDetailsshipmentDetailsregulatoryStatementsLocalizedAttributes $localizedAttributes): self
    {
        $this->initialized['localizedAttributes'] = true;
        $this->localizedAttributes = $localizedAttributes;

        return $this;
    }

    /**
     * Specifies the document identifier.
     *
     * @return list<string>
     */
    public function getDocumentIds(): array
    {
        return $this->documentIds;
    }

    /**
     * Specifies the document identifier.
     *
     * @param list<string> $documentIds
     */
    public function setDocumentIds(array $documentIds): self
    {
        $this->initialized['documentIds'] = true;
        $this->documentIds = $documentIds;

        return $this;
    }

    /**
     * This represents statement url.
     */
    public function getStatementUrl(): string
    {
        return $this->statementUrl;
    }

    /**
     * This represents statement url.
     */
    public function setStatementUrl(string $statementUrl): self
    {
        $this->initialized['statementUrl'] = true;
        $this->statementUrl = $statementUrl;

        return $this;
    }
}
