<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace AntibodiesOnline\FedEx\Model;

class RateV1RatesQuotesPostResponse200OutputRateReplyDetailsItemServiceSubOptionDetail extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * This identifies the indicia used during rate quote.
     *
     * @var string
     */
    protected $smartPostIndiciaType;

    /**
     * This identifies the indicia used during rate quote.
     */
    public function getSmartPostIndiciaType(): string
    {
        return $this->smartPostIndiciaType;
    }

    /**
     * This identifies the indicia used during rate quote.
     */
    public function setSmartPostIndiciaType(string $smartPostIndiciaType): self
    {
        $this->initialized['smartPostIndiciaType'] = true;
        $this->smartPostIndiciaType = $smartPostIndiciaType;

        return $this;
    }
}
