<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace AntibodiesOnline\FedEx\Model;

class RateV1FreightRatesQuotesPostResponse200OutputRateReplyDetailsItemFreightTransitLocationDetailItemDistance extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * Indicate the unit of measure for the distance.
     *
     * @var string
     */
    protected $units;
    /**
     * Indicate the distance. quantity.
     *
     * @var float
     */
    protected $value;

    /**
     * Indicate the unit of measure for the distance.
     */
    public function getUnits(): string
    {
        return $this->units;
    }

    /**
     * Indicate the unit of measure for the distance.
     */
    public function setUnits(string $units): self
    {
        $this->initialized['units'] = true;
        $this->units = $units;

        return $this;
    }

    /**
     * Indicate the distance. quantity.
     */
    public function getValue(): float
    {
        return $this->value;
    }

    /**
     * Indicate the distance. quantity.
     */
    public function setValue(float $value): self
    {
        $this->initialized['value'] = true;
        $this->value = $value;

        return $this;
    }
}
