<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace AntibodiesOnline\FedEx\Model;

class RateV1FreightRatesQuotesPostResponse200OutputRateReplyDetailsItemFreightTransitLocationDetailItemDestinationLocationcontactAndAddressContact extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * Specify contact name.<br>Note: Recommended Length is 70. There's no specific validation for the length.<br> Example: John Taylor.
     *
     * @var string
     */
    protected $personName;
    /**
     * Specify contact email address. Maximum length is 80. <br> Example: sample@company.com.
     *
     * @var string
     */
    protected $emailAddress;
    /**
     * Specify contact phone number. Maximum length is 15. <br> Example: 1234567890.
     *
     * @var string
     */
    protected $phoneNumber;
    /**
     * Specify contact phone extension. Maximum length is 6. <br> Example: 1234.
     *
     * @var string
     */
    protected $phoneExtension;
    /**
     * Specify contact fax number. Maximum length is 15. <br> Example: 1234567890.
     *
     * @var string
     */
    protected $faxNumber;
    /**
     * Specify contact company name. Maximum length is 35.
     *
     * @var string
     */
    protected $companyName;

    /**
     * Specify contact name.<br>Note: Recommended Length is 70. There's no specific validation for the length.<br> Example: John Taylor.
     */
    public function getPersonName(): string
    {
        return $this->personName;
    }

    /**
     * Specify contact name.<br>Note: Recommended Length is 70. There's no specific validation for the length.<br> Example: John Taylor.
     */
    public function setPersonName(string $personName): self
    {
        $this->initialized['personName'] = true;
        $this->personName = $personName;

        return $this;
    }

    /**
     * Specify contact email address. Maximum length is 80. <br> Example: sample@company.com.
     */
    public function getEmailAddress(): string
    {
        return $this->emailAddress;
    }

    /**
     * Specify contact email address. Maximum length is 80. <br> Example: sample@company.com.
     */
    public function setEmailAddress(string $emailAddress): self
    {
        $this->initialized['emailAddress'] = true;
        $this->emailAddress = $emailAddress;

        return $this;
    }

    /**
     * Specify contact phone number. Maximum length is 15. <br> Example: 1234567890.
     */
    public function getPhoneNumber(): string
    {
        return $this->phoneNumber;
    }

    /**
     * Specify contact phone number. Maximum length is 15. <br> Example: 1234567890.
     */
    public function setPhoneNumber(string $phoneNumber): self
    {
        $this->initialized['phoneNumber'] = true;
        $this->phoneNumber = $phoneNumber;

        return $this;
    }

    /**
     * Specify contact phone extension. Maximum length is 6. <br> Example: 1234.
     */
    public function getPhoneExtension(): string
    {
        return $this->phoneExtension;
    }

    /**
     * Specify contact phone extension. Maximum length is 6. <br> Example: 1234.
     */
    public function setPhoneExtension(string $phoneExtension): self
    {
        $this->initialized['phoneExtension'] = true;
        $this->phoneExtension = $phoneExtension;

        return $this;
    }

    /**
     * Specify contact fax number. Maximum length is 15. <br> Example: 1234567890.
     */
    public function getFaxNumber(): string
    {
        return $this->faxNumber;
    }

    /**
     * Specify contact fax number. Maximum length is 15. <br> Example: 1234567890.
     */
    public function setFaxNumber(string $faxNumber): self
    {
        $this->initialized['faxNumber'] = true;
        $this->faxNumber = $faxNumber;

        return $this;
    }

    /**
     * Specify contact company name. Maximum length is 35.
     */
    public function getCompanyName(): string
    {
        return $this->companyName;
    }

    /**
     * Specify contact company name. Maximum length is 35.
     */
    public function setCompanyName(string $companyName): self
    {
        $this->initialized['companyName'] = true;
        $this->companyName = $companyName;

        return $this;
    }
}
