<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace AntibodiesOnline\FedEx\Model;

class RateV1RatesQuotesPostResponse200OutputRateReplyDetailsItemBrokerDetail extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * @var RateV1RatesQuotesPostResponse200OutputRateReplyDetailsItemBrokerDetailBroker
     */
    protected $broker;
    /**
     * This is Broker Type.
     *
     * @var string
     */
    protected $type;
    /**
     * This is the delivery commitment date/time the shipment will arrive at the border. <br> Example: 2019-07-22.
     *
     * @var string
     */
    protected $brokerCommitTimestamp;
    /**
     * This is the delivery commitment day of the week the shipment will arrive at the border. <br> Example: SUNDAY.
     *
     * @var string
     */
    protected $brokerCommitDayOfWeek;
    /**
     * This is the FedEx location identifier for the broker. <br> Example: HKAA.
     *
     * @var string
     */
    protected $brokerLocationId;
    /**
     * This is the broker address used for this shipment.
     *
     * @var RateV1RatesQuotesPostResponse200OutputRateReplyDetailsItemBrokerDetailBrokerAddress
     */
    protected $brokerAddress;
    /**
     * These are number of days it will take for the shipment to make it from broker. <br> Example: 10.
     *
     * @var int
     */
    protected $brokerToDestinationDays;

    public function getBroker(): RateV1RatesQuotesPostResponse200OutputRateReplyDetailsItemBrokerDetailBroker
    {
        return $this->broker;
    }

    public function setBroker(RateV1RatesQuotesPostResponse200OutputRateReplyDetailsItemBrokerDetailBroker $broker): self
    {
        $this->initialized['broker'] = true;
        $this->broker = $broker;

        return $this;
    }

    /**
     * This is Broker Type.
     */
    public function getType(): string
    {
        return $this->type;
    }

    /**
     * This is Broker Type.
     */
    public function setType(string $type): self
    {
        $this->initialized['type'] = true;
        $this->type = $type;

        return $this;
    }

    /**
     * This is the delivery commitment date/time the shipment will arrive at the border. <br> Example: 2019-07-22.
     */
    public function getBrokerCommitTimestamp(): string
    {
        return $this->brokerCommitTimestamp;
    }

    /**
     * This is the delivery commitment date/time the shipment will arrive at the border. <br> Example: 2019-07-22.
     */
    public function setBrokerCommitTimestamp(string $brokerCommitTimestamp): self
    {
        $this->initialized['brokerCommitTimestamp'] = true;
        $this->brokerCommitTimestamp = $brokerCommitTimestamp;

        return $this;
    }

    /**
     * This is the delivery commitment day of the week the shipment will arrive at the border. <br> Example: SUNDAY.
     */
    public function getBrokerCommitDayOfWeek(): string
    {
        return $this->brokerCommitDayOfWeek;
    }

    /**
     * This is the delivery commitment day of the week the shipment will arrive at the border. <br> Example: SUNDAY.
     */
    public function setBrokerCommitDayOfWeek(string $brokerCommitDayOfWeek): self
    {
        $this->initialized['brokerCommitDayOfWeek'] = true;
        $this->brokerCommitDayOfWeek = $brokerCommitDayOfWeek;

        return $this;
    }

    /**
     * This is the FedEx location identifier for the broker. <br> Example: HKAA.
     */
    public function getBrokerLocationId(): string
    {
        return $this->brokerLocationId;
    }

    /**
     * This is the FedEx location identifier for the broker. <br> Example: HKAA.
     */
    public function setBrokerLocationId(string $brokerLocationId): self
    {
        $this->initialized['brokerLocationId'] = true;
        $this->brokerLocationId = $brokerLocationId;

        return $this;
    }

    /**
     * This is the broker address used for this shipment.
     */
    public function getBrokerAddress(): RateV1RatesQuotesPostResponse200OutputRateReplyDetailsItemBrokerDetailBrokerAddress
    {
        return $this->brokerAddress;
    }

    /**
     * This is the broker address used for this shipment.
     */
    public function setBrokerAddress(RateV1RatesQuotesPostResponse200OutputRateReplyDetailsItemBrokerDetailBrokerAddress $brokerAddress): self
    {
        $this->initialized['brokerAddress'] = true;
        $this->brokerAddress = $brokerAddress;

        return $this;
    }

    /**
     * These are number of days it will take for the shipment to make it from broker. <br> Example: 10.
     */
    public function getBrokerToDestinationDays(): int
    {
        return $this->brokerToDestinationDays;
    }

    /**
     * These are number of days it will take for the shipment to make it from broker. <br> Example: 10.
     */
    public function setBrokerToDestinationDays(int $brokerToDestinationDays): self
    {
        $this->initialized['brokerToDestinationDays'] = true;
        $this->brokerToDestinationDays = $brokerToDestinationDays;

        return $this;
    }
}
