<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace AntibodiesOnline\FedEx\Model;

class ShipV1OpenshipmentsRetrievePostResponse200OutputRequestedShipmentRequestedPackageLineItemsItemPackageSpecialServicesSignatureOptionDetail extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * This is release number.<br>Example: 23456.
     *
     * @var string
     */
    protected $signatureReleaseNumber;

    /**
     * This is release number.<br>Example: 23456.
     */
    public function getSignatureReleaseNumber(): string
    {
        return $this->signatureReleaseNumber;
    }

    /**
     * This is release number.<br>Example: 23456.
     */
    public function setSignatureReleaseNumber(string $signatureReleaseNumber): self
    {
        $this->initialized['signatureReleaseNumber'] = true;
        $this->signatureReleaseNumber = $signatureReleaseNumber;

        return $this;
    }
}
