<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace AntibodiesOnline\FedEx\Model;

class ShipV1OpenshipmentsRetrievePostResponse200OutputRequestedShipmentEmailNotificationDetailEmailNotificationRecipientsItem extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * Specify the recipient name.<br>Example: Joe Smith.
     *
     * @var string
     */
    protected $name;
    /**
     * Specify the recipient type for email notification.
     *
     * @var string
     */
    protected $emailNotificationRecipientType;
    /**
     * Specify the recipient email address.<br>Example: xyz@aol.com.
     *
     * @var string
     */
    protected $emailAddress;
    /**
     * This is the format for the email notification. Either HTML or plain text can be provided.<br>Example: TEXT.
     *
     * @var string
     */
    protected $notificationFormatType;
    /**
     * Indicate the type of notification that will be sent as an email<br>Example: EMAIL.
     *
     * @var string
     */
    protected $notificationType;
    /**
     * These are the locale details for email.<br>Example: en_US, fr_CA, es_MX,.etc.<br><a onclick='loadDocReference("locales")'>click here to see Locales</a><br>Note: If the locale is left blank or an invalid locale is entered, an error message is returned in response.
     *
     * @var string
     */
    protected $locale;
    /**
     * These are to specify the notification event types.<br> Example: [ON_PICKUP_DRIVER_ARRIVED, ON_SHIPMENT]<br><a onclick='loadDocReference("notificationeventtypes")'>Click here for more information on Notification Event Types.</a>.
     *
     * @var list<string>
     */
    protected $notificationEventType;

    /**
     * Specify the recipient name.<br>Example: Joe Smith.
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * Specify the recipient name.<br>Example: Joe Smith.
     */
    public function setName(string $name): self
    {
        $this->initialized['name'] = true;
        $this->name = $name;

        return $this;
    }

    /**
     * Specify the recipient type for email notification.
     */
    public function getEmailNotificationRecipientType(): string
    {
        return $this->emailNotificationRecipientType;
    }

    /**
     * Specify the recipient type for email notification.
     */
    public function setEmailNotificationRecipientType(string $emailNotificationRecipientType): self
    {
        $this->initialized['emailNotificationRecipientType'] = true;
        $this->emailNotificationRecipientType = $emailNotificationRecipientType;

        return $this;
    }

    /**
     * Specify the recipient email address.<br>Example: xyz@aol.com.
     */
    public function getEmailAddress(): string
    {
        return $this->emailAddress;
    }

    /**
     * Specify the recipient email address.<br>Example: xyz@aol.com.
     */
    public function setEmailAddress(string $emailAddress): self
    {
        $this->initialized['emailAddress'] = true;
        $this->emailAddress = $emailAddress;

        return $this;
    }

    /**
     * This is the format for the email notification. Either HTML or plain text can be provided.<br>Example: TEXT.
     */
    public function getNotificationFormatType(): string
    {
        return $this->notificationFormatType;
    }

    /**
     * This is the format for the email notification. Either HTML or plain text can be provided.<br>Example: TEXT.
     */
    public function setNotificationFormatType(string $notificationFormatType): self
    {
        $this->initialized['notificationFormatType'] = true;
        $this->notificationFormatType = $notificationFormatType;

        return $this;
    }

    /**
     * Indicate the type of notification that will be sent as an email<br>Example: EMAIL.
     */
    public function getNotificationType(): string
    {
        return $this->notificationType;
    }

    /**
     * Indicate the type of notification that will be sent as an email<br>Example: EMAIL.
     */
    public function setNotificationType(string $notificationType): self
    {
        $this->initialized['notificationType'] = true;
        $this->notificationType = $notificationType;

        return $this;
    }

    /**
     * These are the locale details for email.<br>Example: en_US, fr_CA, es_MX,.etc.<br><a onclick='loadDocReference("locales")'>click here to see Locales</a><br>Note: If the locale is left blank or an invalid locale is entered, an error message is returned in response.
     */
    public function getLocale(): string
    {
        return $this->locale;
    }

    /**
     * These are the locale details for email.<br>Example: en_US, fr_CA, es_MX,.etc.<br><a onclick='loadDocReference("locales")'>click here to see Locales</a><br>Note: If the locale is left blank or an invalid locale is entered, an error message is returned in response.
     */
    public function setLocale(string $locale): self
    {
        $this->initialized['locale'] = true;
        $this->locale = $locale;

        return $this;
    }

    /**
     * These are to specify the notification event types.<br> Example: [ON_PICKUP_DRIVER_ARRIVED, ON_SHIPMENT]<br><a onclick='loadDocReference("notificationeventtypes")'>Click here for more information on Notification Event Types.</a>.
     *
     * @return list<string>
     */
    public function getNotificationEventType(): array
    {
        return $this->notificationEventType;
    }

    /**
     * These are to specify the notification event types.<br> Example: [ON_PICKUP_DRIVER_ARRIVED, ON_SHIPMENT]<br><a onclick='loadDocReference("notificationeventtypes")'>Click here for more information on Notification Event Types.</a>.
     *
     * @param list<string> $notificationEventType
     */
    public function setNotificationEventType(array $notificationEventType): self
    {
        $this->initialized['notificationEventType'] = true;
        $this->notificationEventType = $notificationEventType;

        return $this;
    }
}
