<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace AntibodiesOnline\FedEx\Model;

class ShipV1ShipmentsResultsPostResponse200OutputtransactionShipmentsItemShipmentAdvisoryDetailsRegulatoryAdvisoryProhibitionsItem extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * Indicates the derived harmonized code value<br>Example: 01.
     *
     * @var string
     */
    protected $derivedHarmonizedCode;
    /**
     * Specifies the advisory details.
     *
     * @var ShipV1ShipmentsResultsPostResponse200OutputtransactionShipmentsItemShipmentAdvisoryDetailsRegulatoryAdvisoryProhibitionsItemAdvisory
     */
    protected $advisory;
    /**
     * Indicates one based index identifying the associated commodity.<br>Example: 12.
     *
     * @var int
     */
    protected $commodityIndex;
    /**
     * Indicates the prohibition source type.<br>Example: source.
     *
     * @var string
     */
    protected $source;
    /**
     * Indicate the shipment rule type.<br>Example: ["categories"].
     *
     * @var list<string>
     */
    protected $categories;
    /**
     * Indicates the prohibition type.<br>Example: type.
     *
     * @var string
     */
    protected $type;
    /**
     * Indicates the regulatory waiver.
     *
     * @var ShipV1ShipmentsResultsPostResponse200OutputtransactionShipmentsItemShipmentAdvisoryDetailsRegulatoryAdvisoryProhibitionsItemWaiver
     */
    protected $waiver;
    /**
     * Indicates the prohibitory status.<br>Example: status.
     *
     * @var string
     */
    protected $status;

    /**
     * Indicates the derived harmonized code value<br>Example: 01.
     */
    public function getDerivedHarmonizedCode(): string
    {
        return $this->derivedHarmonizedCode;
    }

    /**
     * Indicates the derived harmonized code value<br>Example: 01.
     */
    public function setDerivedHarmonizedCode(string $derivedHarmonizedCode): self
    {
        $this->initialized['derivedHarmonizedCode'] = true;
        $this->derivedHarmonizedCode = $derivedHarmonizedCode;

        return $this;
    }

    /**
     * Specifies the advisory details.
     */
    public function getAdvisory(): ShipV1ShipmentsResultsPostResponse200OutputtransactionShipmentsItemShipmentAdvisoryDetailsRegulatoryAdvisoryProhibitionsItemAdvisory
    {
        return $this->advisory;
    }

    /**
     * Specifies the advisory details.
     */
    public function setAdvisory(ShipV1ShipmentsResultsPostResponse200OutputtransactionShipmentsItemShipmentAdvisoryDetailsRegulatoryAdvisoryProhibitionsItemAdvisory $advisory): self
    {
        $this->initialized['advisory'] = true;
        $this->advisory = $advisory;

        return $this;
    }

    /**
     * Indicates one based index identifying the associated commodity.<br>Example: 12.
     */
    public function getCommodityIndex(): int
    {
        return $this->commodityIndex;
    }

    /**
     * Indicates one based index identifying the associated commodity.<br>Example: 12.
     */
    public function setCommodityIndex(int $commodityIndex): self
    {
        $this->initialized['commodityIndex'] = true;
        $this->commodityIndex = $commodityIndex;

        return $this;
    }

    /**
     * Indicates the prohibition source type.<br>Example: source.
     */
    public function getSource(): string
    {
        return $this->source;
    }

    /**
     * Indicates the prohibition source type.<br>Example: source.
     */
    public function setSource(string $source): self
    {
        $this->initialized['source'] = true;
        $this->source = $source;

        return $this;
    }

    /**
     * Indicate the shipment rule type.<br>Example: ["categories"].
     *
     * @return list<string>
     */
    public function getCategories(): array
    {
        return $this->categories;
    }

    /**
     * Indicate the shipment rule type.<br>Example: ["categories"].
     *
     * @param list<string> $categories
     */
    public function setCategories(array $categories): self
    {
        $this->initialized['categories'] = true;
        $this->categories = $categories;

        return $this;
    }

    /**
     * Indicates the prohibition type.<br>Example: type.
     */
    public function getType(): string
    {
        return $this->type;
    }

    /**
     * Indicates the prohibition type.<br>Example: type.
     */
    public function setType(string $type): self
    {
        $this->initialized['type'] = true;
        $this->type = $type;

        return $this;
    }

    /**
     * Indicates the regulatory waiver.
     */
    public function getWaiver(): ShipV1ShipmentsResultsPostResponse200OutputtransactionShipmentsItemShipmentAdvisoryDetailsRegulatoryAdvisoryProhibitionsItemWaiver
    {
        return $this->waiver;
    }

    /**
     * Indicates the regulatory waiver.
     */
    public function setWaiver(ShipV1ShipmentsResultsPostResponse200OutputtransactionShipmentsItemShipmentAdvisoryDetailsRegulatoryAdvisoryProhibitionsItemWaiver $waiver): self
    {
        $this->initialized['waiver'] = true;
        $this->waiver = $waiver;

        return $this;
    }

    /**
     * Indicates the prohibitory status.<br>Example: status.
     */
    public function getStatus(): string
    {
        return $this->status;
    }

    /**
     * Indicates the prohibitory status.<br>Example: status.
     */
    public function setStatus(string $status): self
    {
        $this->initialized['status'] = true;
        $this->status = $status;

        return $this;
    }
}
