<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace AntibodiesOnline\FedEx\Model;

class ShipV1ShipmentsResultsPostResponse200OutputtransactionShipmentsItemCompletedShipmentDetailCompletedPackageDetailsItemOperationalDetailOperationalInstructionsItem extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * Specifies the number of operational instructions returned for this shipment.<br>Example: 17.
     *
     * @var int
     */
    protected $number;
    /**
     * This is an operational instruction printed or available on the shipping document.<br>Example: SECURED.
     *
     * @var string
     */
    protected $content;

    /**
     * Specifies the number of operational instructions returned for this shipment.<br>Example: 17.
     */
    public function getNumber(): int
    {
        return $this->number;
    }

    /**
     * Specifies the number of operational instructions returned for this shipment.<br>Example: 17.
     */
    public function setNumber(int $number): self
    {
        $this->initialized['number'] = true;
        $this->number = $number;

        return $this;
    }

    /**
     * This is an operational instruction printed or available on the shipping document.<br>Example: SECURED.
     */
    public function getContent(): string
    {
        return $this->content;
    }

    /**
     * This is an operational instruction printed or available on the shipping document.<br>Example: SECURED.
     */
    public function setContent(string $content): self
    {
        $this->initialized['content'] = true;
        $this->content = $content;

        return $this;
    }
}
