<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace AntibodiesOnline\FedEx\Model;

class ShipV1OpenshipmentsPackagesPostResponse200OutputTransactionShipmentsItemCompletedShipmentDetailServiceDescriptionNamesItem extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * The type of name (long, medium, short, etc.) to which this value refers.<br>Example: long.
     *
     * @var string
     */
    protected $type;
    /**
     * The character encoding used to represent this product name. <br>Example: UTF-8.
     *
     * @var string
     */
    protected $encoding;
    /**
     * Specifies the value of the Product.<br>Example: F-2.
     *
     * @var string
     */
    protected $value;

    /**
     * The type of name (long, medium, short, etc.) to which this value refers.<br>Example: long.
     */
    public function getType(): string
    {
        return $this->type;
    }

    /**
     * The type of name (long, medium, short, etc.) to which this value refers.<br>Example: long.
     */
    public function setType(string $type): self
    {
        $this->initialized['type'] = true;
        $this->type = $type;

        return $this;
    }

    /**
     * The character encoding used to represent this product name. <br>Example: UTF-8.
     */
    public function getEncoding(): string
    {
        return $this->encoding;
    }

    /**
     * The character encoding used to represent this product name. <br>Example: UTF-8.
     */
    public function setEncoding(string $encoding): self
    {
        $this->initialized['encoding'] = true;
        $this->encoding = $encoding;

        return $this;
    }

    /**
     * Specifies the value of the Product.<br>Example: F-2.
     */
    public function getValue(): string
    {
        return $this->value;
    }

    /**
     * Specifies the value of the Product.<br>Example: F-2.
     */
    public function setValue(string $value): self
    {
        $this->initialized['value'] = true;
        $this->value = $value;

        return $this;
    }
}
