<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace AntibodiesOnline\FedEx\Model;

class ShipV1OpenshipmentsRetrievePostResponse200OutputRequestedShipmentCustomsClearanceDetailDeclarationStatementDetailUsmcaLowValueStatementDetail extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * Specify the country Of Origin of Low Value Document for Customs declaration.
     *
     * @var bool
     */
    protected $countryOfOriginLowValueDocumentRequested;
    /**
     * Specify the shipper role for Customs declaration.
     *
     * @var string
     */
    protected $customsRole;

    /**
     * Specify the country Of Origin of Low Value Document for Customs declaration.
     */
    public function getCountryOfOriginLowValueDocumentRequested(): bool
    {
        return $this->countryOfOriginLowValueDocumentRequested;
    }

    /**
     * Specify the country Of Origin of Low Value Document for Customs declaration.
     */
    public function setCountryOfOriginLowValueDocumentRequested(bool $countryOfOriginLowValueDocumentRequested): self
    {
        $this->initialized['countryOfOriginLowValueDocumentRequested'] = true;
        $this->countryOfOriginLowValueDocumentRequested = $countryOfOriginLowValueDocumentRequested;

        return $this;
    }

    /**
     * Specify the shipper role for Customs declaration.
     */
    public function getCustomsRole(): string
    {
        return $this->customsRole;
    }

    /**
     * Specify the shipper role for Customs declaration.
     */
    public function setCustomsRole(string $customsRole): self
    {
        $this->initialized['customsRole'] = true;
        $this->customsRole = $customsRole;

        return $this;
    }
}
