<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace AntibodiesOnline\FedEx\Model;

class TrackV1AssociatedshipmentsPostResponse200OutputCompleteTrackResultsItemTrackResultsItemConsolidationDetailItemReasonDetail extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * Field which holds the reason description. <br> Example: Wrong color.
     *
     * @var string
     */
    protected $description;
    /**
     * Field which holds the reason type.<br> Example: REJECTED.
     *
     * @var string
     */
    protected $type;

    /**
     * Field which holds the reason description. <br> Example: Wrong color.
     */
    public function getDescription(): string
    {
        return $this->description;
    }

    /**
     * Field which holds the reason description. <br> Example: Wrong color.
     */
    public function setDescription(string $description): self
    {
        $this->initialized['description'] = true;
        $this->description = $description;

        return $this;
    }

    /**
     * Field which holds the reason type.<br> Example: REJECTED.
     */
    public function getType(): string
    {
        return $this->type;
    }

    /**
     * Field which holds the reason type.<br> Example: REJECTED.
     */
    public function setType(string $type): self
    {
        $this->initialized['type'] = true;
        $this->type = $type;

        return $this;
    }
}
