<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace AntibodiesOnline\FedEx\Model;

class TrackV1TcnPostResponse200OutputCompleteTrackResultsItemTrackResultsItemDeliveryDetailsDeliveryOptionEligibilityDetailsItem extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * This is the type of delivery option.<br><br><i>Note: For eligibile DISPUTE_DELIVERY, RETURN_TO_SHIPPER, SUPPLEMENT_ADDRESS go to fedex.com to perform the option/action.</i><br><br>Example: INDIRECT_SIGNATURE_RELEASE.
     *
     * @var string
     */
    protected $option;
    /**
     * Eligibility of the customer for the specific delivery options.<br> Example: INELIGIBLE.
     *
     * @var string
     */
    protected $eligibility;

    /**
     * This is the type of delivery option.<br><br><i>Note: For eligibile DISPUTE_DELIVERY, RETURN_TO_SHIPPER, SUPPLEMENT_ADDRESS go to fedex.com to perform the option/action.</i><br><br>Example: INDIRECT_SIGNATURE_RELEASE.
     */
    public function getOption(): string
    {
        return $this->option;
    }

    /**
     * This is the type of delivery option.<br><br><i>Note: For eligibile DISPUTE_DELIVERY, RETURN_TO_SHIPPER, SUPPLEMENT_ADDRESS go to fedex.com to perform the option/action.</i><br><br>Example: INDIRECT_SIGNATURE_RELEASE.
     */
    public function setOption(string $option): self
    {
        $this->initialized['option'] = true;
        $this->option = $option;

        return $this;
    }

    /**
     * Eligibility of the customer for the specific delivery options.<br> Example: INELIGIBLE.
     */
    public function getEligibility(): string
    {
        return $this->eligibility;
    }

    /**
     * Eligibility of the customer for the specific delivery options.<br> Example: INELIGIBLE.
     */
    public function setEligibility(string $eligibility): self
    {
        $this->initialized['eligibility'] = true;
        $this->eligibility = $eligibility;

        return $this;
    }
}
