<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace AntibodiesOnline\FedEx\Exception;

class ModifyOpenShipmentServiceUnavailableException extends ServiceUnavailableException
{
    /**
     * @var \AntibodiesOnline\FedEx\Model\ShipV1OpenshipmentsPutResponse503
     */
    private $shipV1OpenshipmentsPutResponse503;
    /**
     * @var \Psr\Http\Message\ResponseInterface
     */
    private $response;

    public function __construct(\AntibodiesOnline\FedEx\Model\ShipV1OpenshipmentsPutResponse503 $shipV1OpenshipmentsPutResponse503, \Psr\Http\Message\ResponseInterface $response)
    {
        parent::__construct('Service Unavailable');
        $this->shipV1OpenshipmentsPutResponse503 = $shipV1OpenshipmentsPutResponse503;
        $this->response = $response;
    }

    public function getShipV1OpenshipmentsPutResponse503(): \AntibodiesOnline\FedEx\Model\ShipV1OpenshipmentsPutResponse503
    {
        return $this->shipV1OpenshipmentsPutResponse503;
    }

    public function getResponse(): \Psr\Http\Message\ResponseInterface
    {
        return $this->response;
    }
}
