<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace AntibodiesOnline\FedEx\Exception;

class UploadETDFilesServiceUnavailableException extends ServiceUnavailableException
{
    /**
     * @var \AntibodiesOnline\FedEx\Model\DocumentsV1EtdsUploadPostResponse503
     */
    private $documentsV1EtdsUploadPostResponse503;
    /**
     * @var \Psr\Http\Message\ResponseInterface
     */
    private $response;

    public function __construct(\AntibodiesOnline\FedEx\Model\DocumentsV1EtdsUploadPostResponse503 $documentsV1EtdsUploadPostResponse503, \Psr\Http\Message\ResponseInterface $response)
    {
        parent::__construct('Service Unavailable');
        $this->documentsV1EtdsUploadPostResponse503 = $documentsV1EtdsUploadPostResponse503;
        $this->response = $response;
    }

    public function getDocumentsV1EtdsUploadPostResponse503(): \AntibodiesOnline\FedEx\Model\DocumentsV1EtdsUploadPostResponse503
    {
        return $this->documentsV1EtdsUploadPostResponse503;
    }

    public function getResponse(): \Psr\Http\Message\ResponseInterface
    {
        return $this->response;
    }
}
