<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace AntibodiesOnline\FedEx\Exception;

class ValidateAddressInternalServerErrorException extends InternalServerErrorException
{
    /**
     * @var \AntibodiesOnline\FedEx\Model\AddressV1AddressesResolvePostResponse500
     */
    private $addressV1AddressesResolvePostResponse500;
    /**
     * @var \Psr\Http\Message\ResponseInterface
     */
    private $response;

    public function __construct(\AntibodiesOnline\FedEx\Model\AddressV1AddressesResolvePostResponse500 $addressV1AddressesResolvePostResponse500, \Psr\Http\Message\ResponseInterface $response)
    {
        parent::__construct('Failure');
        $this->addressV1AddressesResolvePostResponse500 = $addressV1AddressesResolvePostResponse500;
        $this->response = $response;
    }

    public function getAddressV1AddressesResolvePostResponse500(): \AntibodiesOnline\FedEx\Model\AddressV1AddressesResolvePostResponse500
    {
        return $this->addressV1AddressesResolvePostResponse500;
    }

    public function getResponse(): \Psr\Http\Message\ResponseInterface
    {
        return $this->response;
    }
}
