<?php

namespace AntibodiesOnline\FedEx\Api\Model;

class ShipV1ShipmentsPackagesValidatePostBodyRequestedShipmentCustomsClearanceDetailExportDetail extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];
    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * Use this object to specify the appropriate destination control statement type(s). Also make sure to specify destination country and end user.
     *
     * @var ShipV1ShipmentsPackagesValidatePostBodyRequestedShipmentCustomsClearanceDetailExportDetailDestinationControlDetail
     */
    protected $destinationControlDetail;
    /**
     * Specify the filing option being exercised. Required for  non-document shipments originating in Canada destinated for any country other than Canada, the United States, Puerto Rico, or the U.S. Virgin Islands.
     *
     * @var string
     */
    protected $b13AFilingOption;
    /**
     * For US export shipments requiring an EEI, enter the ITN number received from AES when you filed your shipment or the FTR (Foreign Trade Regulations) exemption number.The proper format for an ITN number is AES XYYYYMMDDNNNNNN where YYYYMMDD is date and NNNNNN are numbers generated by the AES.<br> Example: AESX20220714987654<br>Note: The ITN or FTR exemption number you submit in the ship request prints on the international shipping label.<br><br>For CA export shipments,it can be Proof of report number(15-32 alphanumeric) , Summary proof of report number(7-32 alphanumeric) or Exemption number(2 digit) based on the selected b13AFilingOption.<br>Example: 98765432107654321(POR number), 7654321(Summary POR number) and 02(Exemption number). <br>For FTR exemption number you need provide a predefined value as NO_EEI_30_37_A.
     *
     * @var string
     */
    protected $exportComplianceStatement;
    /**
     * This is a Permit Number. This field is applicable only to Canada export non-document shipments of any value to any destination. No special characters are allowed.<br> Example: 12345
     *
     * @var string
     */
    protected $permitNumber;
    /**
     * Use this object to specify the appropriate destination control statement type(s). Also make sure to specify destination country and end user.
     *
     * @return ShipV1ShipmentsPackagesValidatePostBodyRequestedShipmentCustomsClearanceDetailExportDetailDestinationControlDetail
     */
    public function getDestinationControlDetail(): ShipV1ShipmentsPackagesValidatePostBodyRequestedShipmentCustomsClearanceDetailExportDetailDestinationControlDetail
    {
        return $this->destinationControlDetail;
    }
    /**
     * Use this object to specify the appropriate destination control statement type(s). Also make sure to specify destination country and end user.
     *
     * @param ShipV1ShipmentsPackagesValidatePostBodyRequestedShipmentCustomsClearanceDetailExportDetailDestinationControlDetail $destinationControlDetail
     *
     * @return self
     */
    public function setDestinationControlDetail(ShipV1ShipmentsPackagesValidatePostBodyRequestedShipmentCustomsClearanceDetailExportDetailDestinationControlDetail $destinationControlDetail): self
    {
        $this->initialized['destinationControlDetail'] = true;
        $this->destinationControlDetail = $destinationControlDetail;
        return $this;
    }
    /**
     * Specify the filing option being exercised. Required for  non-document shipments originating in Canada destinated for any country other than Canada, the United States, Puerto Rico, or the U.S. Virgin Islands.
     *
     * @return string
     */
    public function getB13AFilingOption(): string
    {
        return $this->b13AFilingOption;
    }
    /**
     * Specify the filing option being exercised. Required for  non-document shipments originating in Canada destinated for any country other than Canada, the United States, Puerto Rico, or the U.S. Virgin Islands.
     *
     * @param string $b13AFilingOption
     *
     * @return self
     */
    public function setB13AFilingOption(string $b13AFilingOption): self
    {
        $this->initialized['b13AFilingOption'] = true;
        $this->b13AFilingOption = $b13AFilingOption;
        return $this;
    }
    /**
     * For US export shipments requiring an EEI, enter the ITN number received from AES when you filed your shipment or the FTR (Foreign Trade Regulations) exemption number.The proper format for an ITN number is AES XYYYYMMDDNNNNNN where YYYYMMDD is date and NNNNNN are numbers generated by the AES.<br> Example: AESX20220714987654<br>Note: The ITN or FTR exemption number you submit in the ship request prints on the international shipping label.<br><br>For CA export shipments,it can be Proof of report number(15-32 alphanumeric) , Summary proof of report number(7-32 alphanumeric) or Exemption number(2 digit) based on the selected b13AFilingOption.<br>Example: 98765432107654321(POR number), 7654321(Summary POR number) and 02(Exemption number). <br>For FTR exemption number you need provide a predefined value as NO_EEI_30_37_A.
     *
     * @return string
     */
    public function getExportComplianceStatement(): string
    {
        return $this->exportComplianceStatement;
    }
    /**
     * For US export shipments requiring an EEI, enter the ITN number received from AES when you filed your shipment or the FTR (Foreign Trade Regulations) exemption number.The proper format for an ITN number is AES XYYYYMMDDNNNNNN where YYYYMMDD is date and NNNNNN are numbers generated by the AES.<br> Example: AESX20220714987654<br>Note: The ITN or FTR exemption number you submit in the ship request prints on the international shipping label.<br><br>For CA export shipments,it can be Proof of report number(15-32 alphanumeric) , Summary proof of report number(7-32 alphanumeric) or Exemption number(2 digit) based on the selected b13AFilingOption.<br>Example: 98765432107654321(POR number), 7654321(Summary POR number) and 02(Exemption number). <br>For FTR exemption number you need provide a predefined value as NO_EEI_30_37_A.
     *
     * @param string $exportComplianceStatement
     *
     * @return self
     */
    public function setExportComplianceStatement(string $exportComplianceStatement): self
    {
        $this->initialized['exportComplianceStatement'] = true;
        $this->exportComplianceStatement = $exportComplianceStatement;
        return $this;
    }
    /**
     * This is a Permit Number. This field is applicable only to Canada export non-document shipments of any value to any destination. No special characters are allowed.<br> Example: 12345
     *
     * @return string
     */
    public function getPermitNumber(): string
    {
        return $this->permitNumber;
    }
    /**
     * This is a Permit Number. This field is applicable only to Canada export non-document shipments of any value to any destination. No special characters are allowed.<br> Example: 12345
     *
     * @param string $permitNumber
     *
     * @return self
     */
    public function setPermitNumber(string $permitNumber): self
    {
        $this->initialized['permitNumber'] = true;
        $this->permitNumber = $permitNumber;
        return $this;
    }
}