<?php

namespace AntibodiesOnline\FedEx\Api\Model;

class ShipV1OpenshipmentsPackagesPostResponse200OutputTransactionShipmentsItemCompletedShipmentDetail extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];
    public function isInitialized($property) : bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * Indicates the completed package details.
     *
     * @var list<ShipV1OpenshipmentsPackagesPostResponse200OutputTransactionShipmentsItemCompletedShipmentDetailCompletedPackageDetailsItem>
     */
    protected $completedPackageDetails;
    /**
     * Indicates the shipment level operational information.
     *
     * @var ShipV1OpenshipmentsPackagesPostResponse200OutputTransactionShipmentsItemCompletedShipmentDetailOperationalDetail
     */
    protected $operationalDetail;
    /**
     * Specifies which carrier should be included.<br>Example: FDXE
     *
     * @var string
     */
    protected $carrierCode;
    /**
     * This is default holding location information when HOLD_AT_LOCATION special service is requested and the client does not specify the hold location address.
     *
     * @var ShipV1OpenshipmentsPackagesPostResponse200OutputTransactionShipmentsItemCompletedShipmentDetailCompletedHoldAtLocationDetail
     */
    protected $completedHoldAtLocationDetail;
    /**
     * These are completed ETD details when ELECTRONIC_TRADE_DOCUMENTS Special service type is requested
     *
     * @var ShipV1OpenshipmentsPackagesPostResponse200OutputTransactionShipmentsItemCompletedShipmentDetailCompletedEtdDetail
     */
    protected $completedEtdDetail;
    /**
     * Specifies packaging description.
     *
     * @var string
     */
    protected $packagingDescription;
    /**
     * Indicates the tracking details for the package.
     *
     * @var ShipV1OpenshipmentsPackagesPostResponse200OutputTransactionShipmentsItemCompletedShipmentDetailMasterTrackingId
     */
    protected $masterTrackingId;
    /**
     * Descriptions for a service.
     *
     * @var ShipV1OpenshipmentsPackagesPostResponse200OutputTransactionShipmentsItemCompletedShipmentDetailServiceDescription
     */
    protected $serviceDescription;
    /**
     * Indicates whether or not this is an intra-U.S. shipment.
     *
     * @var bool
     */
    protected $usDomestic;
    /**
     * Completed shipment level hazardous commodity information.
     *
     * @var ShipV1OpenshipmentsPackagesPostResponse200OutputTransactionShipmentsItemCompletedShipmentDetailHazardousShipmentDetail
     */
    protected $hazardousShipmentDetail;
    /**
     * All shipment-level rating data for this shipment, which may include data for multiple rate types.
     *
     * @var ShipV1OpenshipmentsPackagesPostResponse200OutputTransactionShipmentsItemCompletedShipmentDetailShipmentRating
     */
    protected $shipmentRating;
    /**
     * Indicates the document requirements detail.
     *
     * @var ShipV1OpenshipmentsPackagesPostResponse200OutputTransactionShipmentsItemCompletedShipmentDetailDocumentRequirements
     */
    protected $documentRequirements;
    /**
     * For US export shipments requiring an EEI, enter the ITN number received from AES when you filed your shipment or the FTR (Foreign Trade Regulations) exemption number.The proper format for an ITN number is AES XYYYYMMDDNNNNNN where YYYYMMDD is date and NNNNNN are numbers generated by the AES.<br> Example: AESX20220714987654<br>Note: The ITN or FTR exemption number you submit in the ship request prints on the international shipping label.<br><br>For CA export shipments,it can be Proof of report number(15-32 alphanumeric) ,Summary proof of report number(7-32 alphanumeric) or Exemption number(2 digit) based on the selected b13AFilingOption.<br>Example: 98765432107654321(POR number), 7654321(Summary POR number) and 02(Exemption number).<br>For FTR exemption number you need provide a predefined value as NO_EEI_30_37_A.
     *
     * @var string
     */
    protected $exportComplianceStatement;
    /**
     * This information describes how and when a online email return label shipment may be accessed for completion.
     *
     * @var ShipV1OpenshipmentsPackagesPostResponse200OutputTransactionShipmentsItemCompletedShipmentDetailAccessDetail
     */
    protected $accessDetail;
    /**
     * Indicates the completed package details.
     *
     * @return list<ShipV1OpenshipmentsPackagesPostResponse200OutputTransactionShipmentsItemCompletedShipmentDetailCompletedPackageDetailsItem>
     */
    public function getCompletedPackageDetails() : array
    {
        return $this->completedPackageDetails;
    }
    /**
     * Indicates the completed package details.
     *
     * @param list<ShipV1OpenshipmentsPackagesPostResponse200OutputTransactionShipmentsItemCompletedShipmentDetailCompletedPackageDetailsItem> $completedPackageDetails
     *
     * @return self
     */
    public function setCompletedPackageDetails(array $completedPackageDetails) : self
    {
        $this->initialized['completedPackageDetails'] = true;
        $this->completedPackageDetails = $completedPackageDetails;
        return $this;
    }
    /**
     * Indicates the shipment level operational information.
     *
     * @return ShipV1OpenshipmentsPackagesPostResponse200OutputTransactionShipmentsItemCompletedShipmentDetailOperationalDetail
     */
    public function getOperationalDetail() : ShipV1OpenshipmentsPackagesPostResponse200OutputTransactionShipmentsItemCompletedShipmentDetailOperationalDetail
    {
        return $this->operationalDetail;
    }
    /**
     * Indicates the shipment level operational information.
     *
     * @param ShipV1OpenshipmentsPackagesPostResponse200OutputTransactionShipmentsItemCompletedShipmentDetailOperationalDetail $operationalDetail
     *
     * @return self
     */
    public function setOperationalDetail(ShipV1OpenshipmentsPackagesPostResponse200OutputTransactionShipmentsItemCompletedShipmentDetailOperationalDetail $operationalDetail) : self
    {
        $this->initialized['operationalDetail'] = true;
        $this->operationalDetail = $operationalDetail;
        return $this;
    }
    /**
     * Specifies which carrier should be included.<br>Example: FDXE
     *
     * @return string
     */
    public function getCarrierCode() : string
    {
        return $this->carrierCode;
    }
    /**
     * Specifies which carrier should be included.<br>Example: FDXE
     *
     * @param string $carrierCode
     *
     * @return self
     */
    public function setCarrierCode(string $carrierCode) : self
    {
        $this->initialized['carrierCode'] = true;
        $this->carrierCode = $carrierCode;
        return $this;
    }
    /**
     * This is default holding location information when HOLD_AT_LOCATION special service is requested and the client does not specify the hold location address.
     *
     * @return ShipV1OpenshipmentsPackagesPostResponse200OutputTransactionShipmentsItemCompletedShipmentDetailCompletedHoldAtLocationDetail
     */
    public function getCompletedHoldAtLocationDetail() : ShipV1OpenshipmentsPackagesPostResponse200OutputTransactionShipmentsItemCompletedShipmentDetailCompletedHoldAtLocationDetail
    {
        return $this->completedHoldAtLocationDetail;
    }
    /**
     * This is default holding location information when HOLD_AT_LOCATION special service is requested and the client does not specify the hold location address.
     *
     * @param ShipV1OpenshipmentsPackagesPostResponse200OutputTransactionShipmentsItemCompletedShipmentDetailCompletedHoldAtLocationDetail $completedHoldAtLocationDetail
     *
     * @return self
     */
    public function setCompletedHoldAtLocationDetail(ShipV1OpenshipmentsPackagesPostResponse200OutputTransactionShipmentsItemCompletedShipmentDetailCompletedHoldAtLocationDetail $completedHoldAtLocationDetail) : self
    {
        $this->initialized['completedHoldAtLocationDetail'] = true;
        $this->completedHoldAtLocationDetail = $completedHoldAtLocationDetail;
        return $this;
    }
    /**
     * These are completed ETD details when ELECTRONIC_TRADE_DOCUMENTS Special service type is requested
     *
     * @return ShipV1OpenshipmentsPackagesPostResponse200OutputTransactionShipmentsItemCompletedShipmentDetailCompletedEtdDetail
     */
    public function getCompletedEtdDetail() : ShipV1OpenshipmentsPackagesPostResponse200OutputTransactionShipmentsItemCompletedShipmentDetailCompletedEtdDetail
    {
        return $this->completedEtdDetail;
    }
    /**
     * These are completed ETD details when ELECTRONIC_TRADE_DOCUMENTS Special service type is requested
     *
     * @param ShipV1OpenshipmentsPackagesPostResponse200OutputTransactionShipmentsItemCompletedShipmentDetailCompletedEtdDetail $completedEtdDetail
     *
     * @return self
     */
    public function setCompletedEtdDetail(ShipV1OpenshipmentsPackagesPostResponse200OutputTransactionShipmentsItemCompletedShipmentDetailCompletedEtdDetail $completedEtdDetail) : self
    {
        $this->initialized['completedEtdDetail'] = true;
        $this->completedEtdDetail = $completedEtdDetail;
        return $this;
    }
    /**
     * Specifies packaging description.
     *
     * @return string
     */
    public function getPackagingDescription() : string
    {
        return $this->packagingDescription;
    }
    /**
     * Specifies packaging description.
     *
     * @param string $packagingDescription
     *
     * @return self
     */
    public function setPackagingDescription(string $packagingDescription) : self
    {
        $this->initialized['packagingDescription'] = true;
        $this->packagingDescription = $packagingDescription;
        return $this;
    }
    /**
     * Indicates the tracking details for the package.
     *
     * @return ShipV1OpenshipmentsPackagesPostResponse200OutputTransactionShipmentsItemCompletedShipmentDetailMasterTrackingId
     */
    public function getMasterTrackingId() : ShipV1OpenshipmentsPackagesPostResponse200OutputTransactionShipmentsItemCompletedShipmentDetailMasterTrackingId
    {
        return $this->masterTrackingId;
    }
    /**
     * Indicates the tracking details for the package.
     *
     * @param ShipV1OpenshipmentsPackagesPostResponse200OutputTransactionShipmentsItemCompletedShipmentDetailMasterTrackingId $masterTrackingId
     *
     * @return self
     */
    public function setMasterTrackingId(ShipV1OpenshipmentsPackagesPostResponse200OutputTransactionShipmentsItemCompletedShipmentDetailMasterTrackingId $masterTrackingId) : self
    {
        $this->initialized['masterTrackingId'] = true;
        $this->masterTrackingId = $masterTrackingId;
        return $this;
    }
    /**
     * Descriptions for a service.
     *
     * @return ShipV1OpenshipmentsPackagesPostResponse200OutputTransactionShipmentsItemCompletedShipmentDetailServiceDescription
     */
    public function getServiceDescription() : ShipV1OpenshipmentsPackagesPostResponse200OutputTransactionShipmentsItemCompletedShipmentDetailServiceDescription
    {
        return $this->serviceDescription;
    }
    /**
     * Descriptions for a service.
     *
     * @param ShipV1OpenshipmentsPackagesPostResponse200OutputTransactionShipmentsItemCompletedShipmentDetailServiceDescription $serviceDescription
     *
     * @return self
     */
    public function setServiceDescription(ShipV1OpenshipmentsPackagesPostResponse200OutputTransactionShipmentsItemCompletedShipmentDetailServiceDescription $serviceDescription) : self
    {
        $this->initialized['serviceDescription'] = true;
        $this->serviceDescription = $serviceDescription;
        return $this;
    }
    /**
     * Indicates whether or not this is an intra-U.S. shipment.
     *
     * @return bool
     */
    public function getUsDomestic() : bool
    {
        return $this->usDomestic;
    }
    /**
     * Indicates whether or not this is an intra-U.S. shipment.
     *
     * @param bool $usDomestic
     *
     * @return self
     */
    public function setUsDomestic(bool $usDomestic) : self
    {
        $this->initialized['usDomestic'] = true;
        $this->usDomestic = $usDomestic;
        return $this;
    }
    /**
     * Completed shipment level hazardous commodity information.
     *
     * @return ShipV1OpenshipmentsPackagesPostResponse200OutputTransactionShipmentsItemCompletedShipmentDetailHazardousShipmentDetail
     */
    public function getHazardousShipmentDetail() : ShipV1OpenshipmentsPackagesPostResponse200OutputTransactionShipmentsItemCompletedShipmentDetailHazardousShipmentDetail
    {
        return $this->hazardousShipmentDetail;
    }
    /**
     * Completed shipment level hazardous commodity information.
     *
     * @param ShipV1OpenshipmentsPackagesPostResponse200OutputTransactionShipmentsItemCompletedShipmentDetailHazardousShipmentDetail $hazardousShipmentDetail
     *
     * @return self
     */
    public function setHazardousShipmentDetail(ShipV1OpenshipmentsPackagesPostResponse200OutputTransactionShipmentsItemCompletedShipmentDetailHazardousShipmentDetail $hazardousShipmentDetail) : self
    {
        $this->initialized['hazardousShipmentDetail'] = true;
        $this->hazardousShipmentDetail = $hazardousShipmentDetail;
        return $this;
    }
    /**
     * All shipment-level rating data for this shipment, which may include data for multiple rate types.
     *
     * @return ShipV1OpenshipmentsPackagesPostResponse200OutputTransactionShipmentsItemCompletedShipmentDetailShipmentRating
     */
    public function getShipmentRating() : ShipV1OpenshipmentsPackagesPostResponse200OutputTransactionShipmentsItemCompletedShipmentDetailShipmentRating
    {
        return $this->shipmentRating;
    }
    /**
     * All shipment-level rating data for this shipment, which may include data for multiple rate types.
     *
     * @param ShipV1OpenshipmentsPackagesPostResponse200OutputTransactionShipmentsItemCompletedShipmentDetailShipmentRating $shipmentRating
     *
     * @return self
     */
    public function setShipmentRating(ShipV1OpenshipmentsPackagesPostResponse200OutputTransactionShipmentsItemCompletedShipmentDetailShipmentRating $shipmentRating) : self
    {
        $this->initialized['shipmentRating'] = true;
        $this->shipmentRating = $shipmentRating;
        return $this;
    }
    /**
     * Indicates the document requirements detail.
     *
     * @return ShipV1OpenshipmentsPackagesPostResponse200OutputTransactionShipmentsItemCompletedShipmentDetailDocumentRequirements
     */
    public function getDocumentRequirements() : ShipV1OpenshipmentsPackagesPostResponse200OutputTransactionShipmentsItemCompletedShipmentDetailDocumentRequirements
    {
        return $this->documentRequirements;
    }
    /**
     * Indicates the document requirements detail.
     *
     * @param ShipV1OpenshipmentsPackagesPostResponse200OutputTransactionShipmentsItemCompletedShipmentDetailDocumentRequirements $documentRequirements
     *
     * @return self
     */
    public function setDocumentRequirements(ShipV1OpenshipmentsPackagesPostResponse200OutputTransactionShipmentsItemCompletedShipmentDetailDocumentRequirements $documentRequirements) : self
    {
        $this->initialized['documentRequirements'] = true;
        $this->documentRequirements = $documentRequirements;
        return $this;
    }
    /**
     * For US export shipments requiring an EEI, enter the ITN number received from AES when you filed your shipment or the FTR (Foreign Trade Regulations) exemption number.The proper format for an ITN number is AES XYYYYMMDDNNNNNN where YYYYMMDD is date and NNNNNN are numbers generated by the AES.<br> Example: AESX20220714987654<br>Note: The ITN or FTR exemption number you submit in the ship request prints on the international shipping label.<br><br>For CA export shipments,it can be Proof of report number(15-32 alphanumeric) ,Summary proof of report number(7-32 alphanumeric) or Exemption number(2 digit) based on the selected b13AFilingOption.<br>Example: 98765432107654321(POR number), 7654321(Summary POR number) and 02(Exemption number).<br>For FTR exemption number you need provide a predefined value as NO_EEI_30_37_A.
     *
     * @return string
     */
    public function getExportComplianceStatement() : string
    {
        return $this->exportComplianceStatement;
    }
    /**
     * For US export shipments requiring an EEI, enter the ITN number received from AES when you filed your shipment or the FTR (Foreign Trade Regulations) exemption number.The proper format for an ITN number is AES XYYYYMMDDNNNNNN where YYYYMMDD is date and NNNNNN are numbers generated by the AES.<br> Example: AESX20220714987654<br>Note: The ITN or FTR exemption number you submit in the ship request prints on the international shipping label.<br><br>For CA export shipments,it can be Proof of report number(15-32 alphanumeric) ,Summary proof of report number(7-32 alphanumeric) or Exemption number(2 digit) based on the selected b13AFilingOption.<br>Example: 98765432107654321(POR number), 7654321(Summary POR number) and 02(Exemption number).<br>For FTR exemption number you need provide a predefined value as NO_EEI_30_37_A.
     *
     * @param string $exportComplianceStatement
     *
     * @return self
     */
    public function setExportComplianceStatement(string $exportComplianceStatement) : self
    {
        $this->initialized['exportComplianceStatement'] = true;
        $this->exportComplianceStatement = $exportComplianceStatement;
        return $this;
    }
    /**
     * This information describes how and when a online email return label shipment may be accessed for completion.
     *
     * @return ShipV1OpenshipmentsPackagesPostResponse200OutputTransactionShipmentsItemCompletedShipmentDetailAccessDetail
     */
    public function getAccessDetail() : ShipV1OpenshipmentsPackagesPostResponse200OutputTransactionShipmentsItemCompletedShipmentDetailAccessDetail
    {
        return $this->accessDetail;
    }
    /**
     * This information describes how and when a online email return label shipment may be accessed for completion.
     *
     * @param ShipV1OpenshipmentsPackagesPostResponse200OutputTransactionShipmentsItemCompletedShipmentDetailAccessDetail $accessDetail
     *
     * @return self
     */
    public function setAccessDetail(ShipV1OpenshipmentsPackagesPostResponse200OutputTransactionShipmentsItemCompletedShipmentDetailAccessDetail $accessDetail) : self
    {
        $this->initialized['accessDetail'] = true;
        $this->accessDetail = $accessDetail;
        return $this;
    }
}